# proto-file: config.proto
# proto-message: UprobestatsConfig

tasks {
    probe_configs: {
        bpf_name: "prog_BitmapAllocation_uprobe_bitmap_creation_for_snapshot"
        file_paths: "/system/framework/framework.jar"
        fully_qualified_class_name: "android.graphics.Bitmap"
        method_name: "<init>"
        fully_qualified_parameters: ["long", "long", "int", "int", "int",
            "boolean", "byte[]",
            "android.graphics.NinePatch$InsetStruct", "boolean"]
    }
    bpf_maps: "map_BitmapAllocation_output"
    target_process_name: "com.android.uprobestats.bitmap"
    target_process_selection: SPECIFIC_APP_PROCESS_ON_START,
    duration_seconds: 10
}
